jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 5
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 120
jobs: 1000
default-resources: "mem_mb=2000"
printshellcmds: true
use-conda: true
