cluster-sync: "srun --partition=all --ntasks=1 --nodes=1 --output=none --error=none --job-name={rule} --cpus-per-task={threads} --mem={resources.mem_mb}"
max-jobs-per-second: 5
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 120
jobs: 1000
default-resources: "mem_mb=2000"
printshellcmds: true
use-conda: true
